[package]
name        = "hello-cpp"
version     = "0.1.0"
description = "Example freight project — multi-file C++"
license     = "MIT"

[language.cpp]
std = "c++23"

[[bin]]
name = "hello-cpp"
src  = "src/main.cpp"

[compiler]
backend   = "auto"
opt-level = 2
debug     = false
warnings  = "all"
includes  = ["inc"]

[profile.debug]
opt-level = 0
debug     = true

[profile.release]
opt-level = 3
lto       = true
strip     = true
debug     = false

[dependencies]
vecmath = "0.1.1"
mathlib = "0.1.0"

[os.unix]
features = ["pthread"]
