//! Serialize [`ImportedProject`] into a `crane.toml` string.
//!
//! The output order is stable so fixture tests can compare byte-for-byte:
//!
//! 1. Header comment (auto-generated marker)
//! 2. `# CRANE:` notes (unimportable constructs, in the order they were recorded)
//! 3. `[package]`
//! 4. `[language.<key>]` sections (sorted)
//! 5. `[lib]` (if any)
//! 6. `[[bin]]` sections (in insertion order)
//! 7. `[dependencies]` (sorted)
//! 8. `[compiler]`
//! 9. `[compiler.includes]` (only when non-empty)
//! 10. `[profile.dev]` / `[profile.release]` (sensible defaults)

use std::fmt::Write as _;

use super::{ImportedDep, ImportedProject};

pub fn to_toml(p: &ImportedProject) -> String {
    let mut out = String::new();

    writeln!(out, "# crane.toml — generated by `crane migrate`").unwrap();
    writeln!(out, "# Review the `# CRANE:` notes below before committing.").unwrap();

    for note in &p.notes {
        writeln!(out, "# CRANE: {note}").unwrap();
    }
    writeln!(out).unwrap();

    // ── [package] ──
    writeln!(out, "[package]").unwrap();
    writeln!(
        out,
        "name        = \"{}\"",
        p.name.as_deref().unwrap_or("imported-project")
    )
    .unwrap();
    writeln!(
        out,
        "version     = \"{}\"",
        p.version.as_deref().unwrap_or("0.1.0")
    )
    .unwrap();
    writeln!(
        out,
        "description = \"{}\"",
        p.description.as_deref().unwrap_or("")
    )
    .unwrap();
    writeln!(out, "license     = \"\"").unwrap();
    writeln!(out).unwrap();

    // ── [language.X] ──
    for (key, lang) in &p.languages {
        writeln!(out, "[language.{key}]").unwrap();
        if let Some(std) = &lang.std {
            writeln!(out, "std = \"{std}\"").unwrap();
        }
        writeln!(out).unwrap();
    }

    // ── [lib] ──
    if let Some(lib) = &p.lib {
        writeln!(out, "[lib]").unwrap();
        writeln!(out, "type    = \"{}\"", lib.lib_type).unwrap();
        writeln!(out, "src     = \"{}\"", lib.src).unwrap();
        if let Some(inc) = &lib.include {
            writeln!(out, "include = \"{inc}\"").unwrap();
        }
        writeln!(out).unwrap();
    }

    // ── [[bin]] ──
    for bin in &p.bins {
        writeln!(out, "[[bin]]").unwrap();
        writeln!(out, "name = \"{}\"", bin.name).unwrap();
        writeln!(out, "src  = \"{}\"", bin.src).unwrap();
        writeln!(out).unwrap();
    }

    // ── [dependencies] ──
    if !p.dependencies.is_empty() {
        writeln!(out, "[dependencies]").unwrap();
        for (name, dep) in &p.dependencies {
            match dep {
                ImportedDep::System(sysname) => {
                    writeln!(out, "{name} = {{ system = \"{sysname}\" }}").unwrap();
                }
                ImportedDep::Version(ver) => {
                    writeln!(out, "{name} = \"{ver}\"").unwrap();
                }
                ImportedDep::Path(rel) => {
                    writeln!(out, "{name} = {{ path = \"{rel}\" }}").unwrap();
                }
            }
        }
        writeln!(out).unwrap();
    }

    // ── [compiler] ──
    writeln!(out, "[compiler]").unwrap();
    writeln!(out, "backend   = \"auto\"").unwrap();
    writeln!(out, "opt-level = 2").unwrap();
    writeln!(out, "debug     = false").unwrap();
    writeln!(out, "warnings  = \"all\"").unwrap();
    if !p.compiler.defines.is_empty() {
        writeln!(out, "defines   = {}", fmt_string_array(&p.compiler.defines)).unwrap();
    }
    if !p.compiler.flags.is_empty() {
        writeln!(out, "flags     = {}", fmt_string_array(&p.compiler.flags)).unwrap();
    }
    writeln!(out).unwrap();

    // ── [compiler.includes] ──
    if !p.compiler.include_paths.is_empty() {
        writeln!(out, "[compiler.includes]").unwrap();
        writeln!(
            out,
            "paths = {}",
            fmt_string_array(&p.compiler.include_paths)
        )
        .unwrap();
        writeln!(out).unwrap();
    }

    // ── [profile.*] defaults ──
    writeln!(out, "[profile.dev]").unwrap();
    writeln!(out, "opt-level = 0").unwrap();
    writeln!(out, "debug     = true").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "[profile.release]").unwrap();
    writeln!(out, "opt-level = 3").unwrap();
    writeln!(out, "lto       = true").unwrap();
    writeln!(out, "strip     = true").unwrap();
    writeln!(out, "debug     = false").unwrap();

    out
}

fn fmt_string_array(items: &[String]) -> String {
    let mut s = String::from("[");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push('"');
        s.push_str(&item.replace('\\', "\\\\").replace('"', "\\\""));
        s.push('"');
    }
    s.push(']');
    s
}

#[cfg(test)]
mod tests {
    use super::super::*;
    use super::*;

    #[test]
    fn minimal_project_emits_package_and_compiler() {
        let p = ImportedProject {
            name: Some("hello".into()),
            version: Some("0.2.0".into()),
            ..Default::default()
        };
        let toml = to_toml(&p);
        assert!(toml.contains("name        = \"hello\""));
        assert!(toml.contains("version     = \"0.2.0\""));
        assert!(toml.contains("[compiler]"));
        assert!(toml.contains("[profile.dev]"));
        assert!(toml.contains("[profile.release]"));
    }

    #[test]
    fn notes_are_emitted_as_crane_comments() {
        let mut p = ImportedProject::default();
        p.push_note("add_subdirectory(sub) not imported");
        let toml = to_toml(&p);
        assert!(toml.contains("# CRANE: add_subdirectory(sub) not imported"));
    }

    #[test]
    fn system_and_path_deps_emit_tables() {
        let mut p = ImportedProject::default();
        p.dependencies
            .insert("openssl".into(), ImportedDep::System("openssl".into()));
        p.dependencies
            .insert("myutils".into(), ImportedDep::Path("../myutils".into()));
        let toml = to_toml(&p);
        assert!(toml.contains("openssl = { system = \"openssl\" }"));
        assert!(toml.contains("myutils = { path = \"../myutils\" }"));
    }
}
