use std::path::{Component, Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::build::deps::ResolvedDep;
use crate::git;
use crate::manifest::types::{Dependency, Manifest};

const LOCK_VERSION: u32 = 1;
const HEADER: &str = "# This file is automatically @generated by crane.\n# Do not edit manually.\n";

// ── Types ─────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Deserialize, Serialize, Default)]
pub struct LockFile {
    pub version: u32,
    #[serde(rename = "package", default)]
    pub packages: Vec<LockPackage>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct LockPackage {
    pub name: String,
    pub version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

// ── I/O ───────────────────────────────────────────────────────────────────────

impl LockFile {
    pub fn load(project_dir: &Path) -> Option<Self> {
        let src = std::fs::read_to_string(project_dir.join("crane.lock")).ok()?;
        toml_edit::de::from_str(&src).ok()
    }

    pub fn save(&self, project_dir: &Path) -> std::io::Result<()> {
        std::fs::write(project_dir.join("crane.lock"), self.render())
    }

    /// Generate a lockfile from the resolved dep graph.
    pub fn generate(project_dir: &Path, root: &Manifest, resolved: &[ResolvedDep]) -> Self {
        let mut packages: Vec<LockPackage> = Vec::new();

        // Root package
        let mut root_dep_names: Vec<String> = root.dependencies.keys().cloned().collect();
        root_dep_names.sort();
        packages.push(LockPackage {
            name: root.package.name.clone(),
            version: root.package.version.clone(),
            source: None,
            checksum: None,
            dependencies: root_dep_names,
        });

        // Compiled deps (path / version / git — all are present in resolved)
        for dep in resolved {
            let source = dep_source_string(project_dir, dep, root);
            let checksum = dep_checksum(&dep.dir);
            let mut dep_dep_names: Vec<String> =
                dep.manifest.dependencies.keys().cloned().collect();
            dep_dep_names.sort();
            packages.push(LockPackage {
                name: dep.name.clone(),
                version: dep.manifest.package.version.clone(),
                source: Some(source),
                checksum,
                dependencies: dep_dep_names,
            });
        }

        // System deps: recorded with source = "system", no version or checksum
        for (name, dep) in &root.dependencies {
            if let Dependency::Detailed(d) = dep {
                if d.system.is_some() {
                    packages.push(LockPackage {
                        name: name.clone(),
                        version: String::new(),
                        source: Some("system".to_string()),
                        checksum: None,
                        dependencies: vec![],
                    });
                }
            }
        }

        packages.sort_by(|a, b| a.name.cmp(&b.name));
        LockFile { version: LOCK_VERSION, packages }
    }

    /// Pretty-print the lockfile in a deterministic, human-readable TOML form.
    fn render(&self) -> String {
        let mut out = HEADER.to_string();
        out.push_str(&format!("version = {}\n", self.version));
        for pkg in &self.packages {
            out.push('\n');
            out.push_str("[[package]]\n");
            out.push_str(&format!("name    = {:?}\n", pkg.name));
            if !pkg.version.is_empty() {
                out.push_str(&format!("version = {:?}\n", pkg.version));
            }
            if let Some(src) = &pkg.source {
                out.push_str(&format!("source  = {:?}\n", src));
            }
            if let Some(ck) = &pkg.checksum {
                out.push_str(&format!("checksum = {:?}\n", ck));
            }
            if !pkg.dependencies.is_empty() {
                out.push_str("dependencies = [\n");
                for d in &pkg.dependencies {
                    out.push_str(&format!("    {:?},\n", d));
                }
                out.push_str("]\n");
            }
        }
        out
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn dep_source_string(project_dir: &Path, dep: &ResolvedDep, root_manifest: &Manifest) -> String {
    if let Some(Dependency::Detailed(d)) = root_manifest.dependencies.get(&dep.name) {
        if let Some(url) = &d.git {
            let sha = git::current_rev(&dep.dir).unwrap_or_else(|| "HEAD".to_string());
            return format!("git+{}#{}", url, sha);
        }
    }
    let rel = relative_path(project_dir, &dep.dir);
    format!("path+{}", rel.display())
}

fn dep_checksum(dep_dir: &Path) -> Option<String> {
    let content = std::fs::read(dep_dir.join("crane.toml")).ok()?;
    let mut h = Sha256::new();
    h.update(&content);
    Some(format!("sha256:{:x}", h.finalize()))
}

/// Compute `to` relative to `from` (both should be absolute).
/// Falls back to the absolute path if a relative path cannot be formed.
pub fn relative_path(from: &Path, to: &Path) -> PathBuf {
    let from_comps: Vec<Component> = from.components().collect();
    let to_comps: Vec<Component> = to.components().collect();

    let common = from_comps
        .iter()
        .zip(to_comps.iter())
        .take_while(|(a, b)| a == b)
        .count();

    let up_count = from_comps.len() - common;
    let mut result = PathBuf::new();
    for _ in 0..up_count {
        result.push("..");
    }
    for comp in &to_comps[common..] {
        result.push(comp);
    }

    if result.as_os_str().is_empty() {
        PathBuf::from(".")
    } else {
        result
    }
}
