//! Rendering for the **system-side registry**: a directory of `[package]` stub
//! `.toml` files, one per pkg-config package installed on the host. The
//! `freight-system-registry` executable populates it — preferring an upstream
//! registry's metadata, falling back to a stub described by the system package
//! manager — so freight can resolve locally-installed libraries without hitting
//! the network.

/// The system-side registry directory: `$FREIGHT_HOME/registries/system`. This
/// is where `freight-system-registry` writes stubs and where the `"system"` repo
/// reads them. `None` when no FREIGHT_HOME can be determined.
pub fn system_registry_dir() -> Option<std::path::PathBuf> {
    crate::toolchain::cache::freight_home().map(|h| h.join("registries").join("system"))
}

/// Where a stub's metadata came from (recorded as a comment for transparency).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StubSource {
    /// Pulled from a freight registry.
    Registry,
    /// Synthesized from pkg-config + the system package manager.
    System,
}

impl StubSource {
    fn label(self) -> &'static str {
        match self {
            StubSource::Registry => "registry",
            StubSource::System => "system",
        }
    }
}

/// Render a `[package]` stub `.toml`. An empty `version` becomes `"*"`; the
/// description is TOML-escaped onto a single line.
pub fn render_package_stub(
    name: &str,
    version: &str,
    description: &str,
    source: StubSource,
) -> String {
    let ver = if version.trim().is_empty() {
        "*"
    } else {
        version.trim()
    };
    format!(
        "# generated by freight-system-registry ({})\n\
         [package]\n\
         name        = \"{name}\"\n\
         version     = \"{ver}\"\n\
         description = \"{}\"\n",
        source.label(),
        toml_escape(description),
    )
}

/// Escape a string for a double-quoted TOML basic string, collapsing newlines.
fn toml_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace(['\n', '\r', '\t'], " ")
        .trim()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_a_valid_parseable_stub() {
        let toml = render_package_stub("zlib", "1.3.2", "Compression library", StubSource::System);
        let parsed: toml::Value = toml.parse().expect("stub must be valid TOML");
        let pkg = parsed.get("package").unwrap();
        assert_eq!(pkg.get("name").unwrap().as_str(), Some("zlib"));
        assert_eq!(pkg.get("version").unwrap().as_str(), Some("1.3.2"));
        assert_eq!(
            pkg.get("description").unwrap().as_str(),
            Some("Compression library")
        );
        assert!(toml.contains("(system)"));
    }

    #[test]
    fn empty_version_becomes_star_and_description_is_escaped() {
        let toml = render_package_stub(
            "weird",
            "",
            "has \"quotes\"\nand newlines",
            StubSource::Registry,
        );
        let parsed: toml::Value = toml.parse().expect("escaped stub must parse");
        let pkg = parsed.get("package").unwrap();
        assert_eq!(pkg.get("version").unwrap().as_str(), Some("*"));
        assert_eq!(
            pkg.get("description").unwrap().as_str(),
            Some("has \"quotes\" and newlines")
        );
        assert!(toml.contains("(registry)"));
    }
}
