#include <cstdio>
#include "version.h"   // generated by build.crane into target/dev/build/

int main() {
    std::printf("%s %s (git: %s)\n",
        PROJECT_NAME,
        PROJECT_VERSION,
        GIT_HASH);

#if defined(PLATFORM_LINUX)
    std::printf("Platform: Linux\n");
#elif defined(PLATFORM_MACOS)
    std::printf("Platform: macOS\n");
#elif defined(PLATFORM_WINDOWS)
    std::printf("Platform: Windows\n");
#else
    std::printf("Platform: unknown\n");
#endif

    return 0;
}
