#include <cstdio>
#include "version.h"   // generated by build.freight into target/dev/build/

int main() {
    std::printf("%s %s (git: %s)\n",
        PROJECT_NAME, PROJECT_VERSION, GIT_HASH);

#if defined(HAVE_ZLIB)
    std::printf("zlib: yes\n");
#else
    std::printf("zlib: no\n");
#endif

    return 0;
}
