//! A [`PackageRepo`] backed by a local directory of `[package]` stub `.toml`
//! files — one per package, named `<package>.toml`. This is how freight consumes
//! the **system-side registry** generated by `freight-system-registry`: package
//! metadata for locally-installed libraries, with no network access.
//!
//! It is registered as the `"system"` repo and consulted first by the CMake
//! dependency resolver, so a `find_package` name that names a locally-available
//! library resolves without reaching for the network or marking it external.

use std::path::{Path, PathBuf};

use super::{PackageInfo, PackageRepo, PackageVersion, UserProfile};
use crate::error::FreightError;

/// A registry served from a directory of `[package]` stub `.toml` files.
pub struct DirectoryRegistry {
    dir: PathBuf,
    key: String,
}

impl DirectoryRegistry {
    /// A directory registry rooted at `dir`, advertised under `key`.
    pub fn new(dir: impl Into<PathBuf>, key: impl Into<String>) -> Self {
        Self {
            dir: dir.into(),
            key: key.into(),
        }
    }

    /// The system-side registry at `$FREIGHT_HOME/registries/system`, if a
    /// FREIGHT_HOME can be determined. Returns `None` when it can't (so callers
    /// can simply skip it).
    pub fn system() -> Option<Self> {
        crate::resolve::system_registry::system_registry_dir()
            .map(|dir| Self::new(dir, "system"))
    }

    /// Parse `<dir>/<name>.toml` into a [`PackageInfo`]. `Ok(None)` when absent.
    fn read_stub(&self, name: &str) -> Result<Option<PackageInfo>, FreightError> {
        let path = self.dir.join(format!("{name}.toml"));
        if !path.is_file() {
            return Ok(None);
        }
        parse_stub(&path).map(Some)
    }
}

/// Parse a single `[package]` stub file into [`PackageInfo`].
fn parse_stub(path: &Path) -> Result<PackageInfo, FreightError> {
    let text = std::fs::read_to_string(path)?;
    let value: toml::Value = text
        .parse()
        .map_err(|e: toml::de::Error| FreightError::ManifestParse(e.to_string()))?;
    let pkg = value.get("package").ok_or_else(|| {
        FreightError::ManifestParse(format!("{}: missing [package]", path.display()))
    })?;
    let name = pkg
        .get("name")
        .and_then(|v| v.as_str())
        .map(str::to_string)
        .or_else(|| path.file_stem().and_then(|s| s.to_str()).map(str::to_string))
        .ok_or_else(|| FreightError::ManifestParse(format!("{}: no package name", path.display())))?;
    let version = pkg
        .get("version")
        .and_then(|v| v.as_str())
        .unwrap_or("*")
        .to_string();
    let description = pkg
        .get("description")
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .map(str::to_string);

    Ok(PackageInfo {
        name,
        description,
        latest: version.clone(),
        versions: vec![PackageVersion {
            version,
            checksum: None,
            download_url: None,
            upstream_url: None,
            build_system: None,
            prebuilt_triples: Vec::new(),
            dependencies: std::collections::HashMap::new(),
            downloads: 0,
        }],
        keywords: Vec::new(),
        owners: Vec::new(),
    })
}

impl PackageRepo for DirectoryRegistry {
    fn repo_key(&self) -> &str {
        &self.key
    }

    fn lookup(
        &self,
        name: &str,
        _channel: Option<&str>,
    ) -> Result<Option<PackageInfo>, FreightError> {
        self.read_stub(name)
    }

    fn search(&self, query: &str) -> Result<Vec<PackageInfo>, FreightError> {
        let mut hits = Vec::new();
        let Ok(entries) = std::fs::read_dir(&self.dir) else {
            return Ok(hits);
        };
        let needle = query.to_lowercase();
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("toml") {
                continue;
            }
            let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
            if needle.is_empty() || stem.to_lowercase().contains(&needle) {
                if let Ok(info) = parse_stub(&path) {
                    hits.push(info);
                }
            }
        }
        hits.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(hits)
    }

    fn fetch_readme(&self, _name: &str) -> Option<String> {
        None
    }

    fn fetch_user_profile(&self, _username: &str) -> Option<UserProfile> {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(dir: &Path, name: &str, body: &str) {
        std::fs::write(dir.join(format!("{name}.toml")), body).unwrap();
    }

    #[test]
    fn lookup_and_search_over_stub_files() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        write(
            dir,
            "zlib",
            "[package]\nname = \"zlib\"\nversion = \"1.3.2\"\ndescription = \"Compression library\"\n",
        );
        write(
            dir,
            "zstd",
            "[package]\nname = \"libzstd\"\nversion = \"1.5.6\"\n",
        );

        let reg = DirectoryRegistry::new(dir, "system");
        assert_eq!(reg.repo_key(), "system");

        let z = reg.lookup("zlib", None).unwrap().expect("zlib present");
        assert_eq!(z.latest, "1.3.2");
        assert_eq!(z.description.as_deref(), Some("Compression library"));

        // Missing file → Ok(None), never an error.
        assert!(reg.lookup("nonexistent", None).unwrap().is_none());

        // Search matches by file stem; missing description is fine.
        let hits = reg.search("z").unwrap();
        assert_eq!(hits.len(), 2);
        assert_eq!(hits[0].name, "libzstd"); // package name from inside the stub
    }
}
