#include <stdio.h>
#include "build_info.h"   /* generated by build.freight into target/{profile}/build/ */

int main(void) {
    const BuildInfo *b = build_info();

    printf("prebuilt-demo\n");
    printf("=============\n");
    printf("name:     %s\n", b->name);
    printf("version:  %s\n", b->version);
    printf("profile:  %s\n", b->profile);
    printf("git:      %s\n", b->git_hash);

#ifdef HAVE_ZLIB
    printf("zlib:     yes  (linked via pkg-config)\n");
#else
    printf("zlib:     no   (install zlib-dev + re-run freight build)\n");
#endif

    return 0;
}
