//! Conan C/C++ package manager integration.
//!
//! Installs packages into `.deps/conan/<name>/` using the `PkgConfigDeps`
//! generator, then queries the resulting `.pc` files via pkg-config.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::error::FreightError;
use crate::event::{BuildEvent, Progress};
use crate::meta::pkg_config::{PkgConfigResult, pkg_config_query_with_path};
use crate::meta::ForeignBuilt;

/// Return `true` if a `conan` binary is available on `PATH`.
pub fn is_conan_available() -> bool {
    Command::new("conan")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Install `package/version` via conan and return the resolved libs and include dirs.
///
/// The package is installed into `.deps/conan/<name>/` with the `PkgConfigDeps`
/// generator. The resulting `.pc` files are then queried via pkg-config.
pub fn resolve_conan_dep(
    name: &str,
    package: &str,
    version: &str,
    project_dir: &Path,
    progress: &Progress,
) -> Result<ForeignBuilt, FreightError> {
    let conan_dir = project_dir.join(".deps").join("conan").join(name);
    std::fs::create_dir_all(&conan_dir)?;

    progress(BuildEvent::ResolvingDep {
        name: name.to_string(),
        via: "conan".to_string(),
    });

    let requires = if version.is_empty() || version == "*" {
        package.to_string()
    } else {
        format!("{package}/{version}")
    };

    let conanfile = format!(
        "[requires]\n{requires}\n\n[generators]\nPkgConfigDeps\n"
    );
    std::fs::write(conan_dir.join("conanfile.txt"), &conanfile)?;

    let status = Command::new("conan")
        .args(["install", ".", "--build=missing", "--output-folder=."])
        .current_dir(&conan_dir)
        .status()
        .map_err(|e| FreightError::CompilerNotFound(format!("conan not found: {e}")))?;

    if !status.success() {
        return Err(FreightError::CompileFailed(
            name.to_string(),
            format!("conan install exited with status {}", status.code().unwrap_or(-1)),
        ));
    }

    // Collect all directories that contain .pc files generated by conan.
    let pc_dirs = find_pc_dirs(&conan_dir);

    // Use the bare package name (not the version constraint) as the pkg-config query.
    let pc_name = package.split('/').next().unwrap_or(package);
    match pkg_config_query_with_path(pc_name, &pc_dirs) {
        Ok(PkgConfigResult { include_dirs, link_flags }) => Ok(ForeignBuilt {
            name: name.to_string(),
            libs: vec![],
            include_dirs,
            raw_link_flags: link_flags,
        }),
        Err(_) => {
            // pkg-config .pc not generated — collect libs directly from conan output.
            let libs = collect_libs(&conan_dir);
            let include_dirs = collect_includes(&conan_dir);
            Ok(ForeignBuilt { name: name.to_string(), libs, include_dirs, raw_link_flags: vec![] })
        }
    }
}

fn find_pc_dirs(conan_dir: &Path) -> Vec<PathBuf> {
    let mut dirs: Vec<PathBuf> = Vec::new();
    // Conan PkgConfigDeps outputs .pc files in <output-folder>/ or sub-directories.
    for entry in walkdir::WalkDir::new(conan_dir)
        .max_depth(3)
        .follow_links(false)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        if entry.path().extension().is_some_and(|e| e == "pc") {
            if let Some(dir) = entry.path().parent() {
                if !dirs.iter().any(|d| d == dir) {
                    dirs.push(dir.to_path_buf());
                }
            }
        }
    }
    dirs
}

fn collect_libs(conan_dir: &Path) -> Vec<PathBuf> {
    let mut libs = Vec::new();
    for entry in walkdir::WalkDir::new(conan_dir)
        .follow_links(false)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        if let Some(ext) = entry.path().extension().and_then(|e| e.to_str()) {
            if matches!(ext, "a" | "so" | "dylib" | "lib") {
                libs.push(entry.into_path());
            }
        }
    }
    libs.sort();
    libs
}

fn collect_includes(conan_dir: &Path) -> Vec<PathBuf> {
    let candidate = conan_dir.join("include");
    if candidate.is_dir() { vec![candidate] } else { vec![] }
}
