[package]
name        = "bcrypt"
version     = "0"
description = "Windows CNG — modern cryptography: AES, RSA, EC, hashing, key derivation"
supports    = "windows"

[lib]
type = "system"
link = "bcrypt"
hdrs = ["bcrypt.h"]
