[package]
name        = "comctl32"
version     = "0"
description = "Common controls — toolbar, listview, treeview, progress bar, tab control"
supports    = "windows"

[lib]
type = "system"
link = "comctl32"
hdrs = ["commctrl.h"]
