[package]
name        = "kernel32"
version     = "0"
description = "Win32 kernel — processes, threads, memory, file I/O, synchronisation"
supports    = "windows"

[lib]
type = "system"
link = "kernel32"
hdrs = ["windows.h"]
