[package]
name        = "ntdll"
version     = "0"
description = "NT layer — low-level NT system calls, RtlXxx heap/string utilities, LDR loader"
supports    = "windows"

[lib]
type = "system"
link = "ntdll"
hdrs = ["winternl.h"]
