[package]
name        = "pthread"
version     = "0"
description = "POSIX threads — synchronisation primitives, thread creation and management"
supports    = "unix"

[lib]
type = "system"
link = "pthread"
hdrs = ["pthread.h", "semaphore.h", "sched.h"]
