[package]
name        = "resolv"
version     = "0"
description = "DNS resolver — res_query, res_search, dn_expand"
supports    = "unix"

[lib]
type = "system"
link = "resolv"
hdrs = ["resolv.h", "netdb.h", "arpa/nameser.h"]
