[package]
name        = "rt"
version     = "0"
description = "POSIX real-time extensions — clocks, timers, POSIX shared memory, message queues"
supports    = "linux | solaris | illumos"

[lib]
type = "system"
link = "rt"
hdrs = ["time.h", "mqueue.h", "aio.h"]
