[package]
name        = "setupapi"
version     = "0"
description = "Setup API — device enumeration, driver installation, hardware information"
supports    = "windows"

[lib]
type = "system"
link = "setupapi"
hdrs = ["setupapi.h", "devguid.h"]
