//! Serialize [`ImportedProject`] into a `freight.toml` string.
//!
//! The output order is stable so fixture tests can compare byte-for-byte:
//!
//! 1. Header comment (auto-generated marker)
//! 2. `# FREIGHT:` notes (unimportable constructs, in the order they were recorded)
//! 3. `[package]`
//! 4. `[language.<key>]` sections (sorted)
//! 5. `[lib]` (if any)
//! 6. `[[bin]]` sections (in insertion order)
//! 7. `[dependencies]` (sorted)
//! 8. `[compiler]`
//! 9. `[compiler.includes]` (only when non-empty)
//! 10. `[profile.dev]` / `[profile.release]` (sensible defaults)

use std::fmt::Write as _;

use crate::{ImportedDep, ImportedLib, ImportedProject};

pub fn to_toml(p: &ImportedProject) -> String {
    let mut out = String::new();

    writeln!(out, "# freight.toml — generated by `freight migrate`").unwrap();
    writeln!(out, "# Review the `# FREIGHT:` notes below before committing.").unwrap();
    for note in &p.notes {
        writeln!(out, "# FREIGHT: {note}").unwrap();
    }
    writeln!(out).unwrap();

    // ── [package] ──
    writeln!(out, "[package]").unwrap();
    writeln!(out, "name        = \"{}\"", p.name.as_deref().unwrap_or("imported-project")).unwrap();
    writeln!(out, "version     = \"{}\"", p.version.as_deref().unwrap_or("0.1.0")).unwrap();
    if let Some(desc) = p.description.as_deref().filter(|d| !d.is_empty()) {
        writeln!(out, "description = \"{}\"", escape_string(desc)).unwrap();
    }
    writeln!(out).unwrap();

    emit_languages(&mut out, p);

    // ── [lib] — only the first library is emitted; extras become notes ──
    if let Some(lib) = p.libs.first() {
        writeln!(out, "[lib]").unwrap();
        writeln!(out, "type    = \"{}\"", lib.lib_type).unwrap();
        writeln!(out, "src     = \"{}\"", lib.src).unwrap();
        if let Some(inc) = &lib.include {
            writeln!(out, "include = \"{inc}\"").unwrap();
        }
        writeln!(out).unwrap();
    }

    // ── [[bin]] ──
    for bin in &p.bins {
        writeln!(out, "[[bin]]").unwrap();
        writeln!(out, "name = \"{}\"", bin.name).unwrap();
        writeln!(out, "src  = \"{}\"", bin.src).unwrap();
        writeln!(out).unwrap();
    }

    emit_dependencies(&mut out, p);
    emit_compiler_sections(&mut out, p);
    emit_platform_sections(&mut out, p);
    emit_profiles(&mut out);

    out
}

// ── Workspace emission ────────────────────────────────────────────────────────

/// Output of [`to_workspace_toml`].
pub struct WorkspaceOutput {
    /// Contents of the workspace-root `freight.toml`.
    pub root_toml: String,
    /// `(relative_dir_name, freight.toml_contents)` for each member.
    pub members: Vec<(String, String)>,
}

/// Serialize a multi-library [`ImportedProject`] into a workspace.
///
/// Produces one `[workspace]` root manifest and one member manifest per
/// library plus one shared binary member. Libraries become `[lib]` members;
/// binaries (if any) become a single `[[bin]]` member that path-depends on
/// every library member.
pub fn to_workspace_toml(p: &ImportedProject) -> WorkspaceOutput {
    let mut members: Vec<(String, String)> = Vec::new();

    // One member per library.
    for lib in &p.libs {
        let dir_name = sanitise_name(&lib.name);
        let toml = emit_lib_member(p, lib, &dir_name);
        members.push((dir_name, toml));
    }

    // One member for the binary targets (if any), with path deps to all libs.
    if !p.bins.is_empty() {
        let bin_member_name = p.name.as_deref().unwrap_or("app").to_string();
        let dir_name = sanitise_name(&bin_member_name);
        let lib_paths: Vec<String> = members.iter().map(|(d, _)| format!("../{d}")).collect();
        let toml = emit_bin_member(p, &bin_member_name, &lib_paths);
        members.push((dir_name, toml));
    }

    // Root workspace manifest.
    let member_list: Vec<String> = members.iter().map(|(d, _)| format!("{d}/")).collect();
    let mut root = String::new();
    writeln!(root, "# freight.toml — generated by `freight migrate` (workspace root)").unwrap();
    writeln!(root, "# Review the `# FREIGHT:` notes in each member's freight.toml.").unwrap();
    writeln!(root).unwrap();
    writeln!(root, "[workspace]").unwrap();
    write!(root, "members = [").unwrap();
    for (i, m) in member_list.iter().enumerate() {
        if i > 0 { write!(root, ", ").unwrap(); }
        write!(root, "\"{m}\"").unwrap();
    }
    writeln!(root, "]").unwrap();

    WorkspaceOutput { root_toml: root, members }
}

fn emit_lib_member(p: &ImportedProject, lib: &ImportedLib, _dir: &str) -> String {
    let mut out = String::new();
    writeln!(out, "# freight.toml — generated by `freight migrate`").unwrap();
    writeln!(out, "# Review the `# FREIGHT:` notes below before committing.").unwrap();
    for note in &p.notes {
        writeln!(out, "# FREIGHT: {note}").unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "[package]").unwrap();
    writeln!(out, "name        = \"{}\"", lib.name).unwrap();
    writeln!(out, "version     = \"{}\"", p.version.as_deref().unwrap_or("0.1.0")).unwrap();
    writeln!(out).unwrap();

    emit_languages(&mut out, p);

    writeln!(out, "[lib]").unwrap();
    writeln!(out, "type    = \"{}\"", lib.lib_type).unwrap();
    writeln!(out, "src     = \"{}\"", lib.src).unwrap();
    if let Some(inc) = &lib.include {
        writeln!(out, "include = \"{inc}\"").unwrap();
    }
    writeln!(out).unwrap();

    emit_dependencies(&mut out, p);
    emit_compiler_sections(&mut out, p);
    emit_platform_sections(&mut out, p);
    emit_profiles(&mut out);

    out
}

fn emit_bin_member(p: &ImportedProject, pkg_name: &str, lib_paths: &[String]) -> String {
    let mut out = String::new();
    writeln!(out, "# freight.toml — generated by `freight migrate`").unwrap();
    writeln!(out, "# Review the `# FREIGHT:` notes below before committing.").unwrap();
    for note in &p.notes {
        writeln!(out, "# FREIGHT: {note}").unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "[package]").unwrap();
    writeln!(out, "name        = \"{}\"", pkg_name).unwrap();
    writeln!(out, "version     = \"{}\"", p.version.as_deref().unwrap_or("0.1.0")).unwrap();
    writeln!(out).unwrap();

    emit_languages(&mut out, p);

    for bin in &p.bins {
        writeln!(out, "[[bin]]").unwrap();
        writeln!(out, "name = \"{}\"", bin.name).unwrap();
        writeln!(out, "src  = \"{}\"", bin.src).unwrap();
        writeln!(out).unwrap();
    }

    // Merge project-level deps + path deps to library members.
    let has_non_lib_deps = !p.dependencies.is_empty();
    let has_lib_paths = !lib_paths.is_empty();
    if has_non_lib_deps || has_lib_paths {
        writeln!(out, "[dependencies]").unwrap();
        for path in lib_paths {
            let dep_name = path.trim_start_matches("../");
            writeln!(out, "{dep_name} = {{ path = \"{path}\" }}").unwrap();
        }
        for (name, dep) in &p.dependencies {
            match dep {
                ImportedDep::System(s) => writeln!(out, "{name} = {{ system = \"{s}\" }}").unwrap(),
                ImportedDep::Version(v) => writeln!(out, "{name} = \"{v}\"").unwrap(),
                ImportedDep::Path(r) => writeln!(out, "{name} = {{ path = \"{r}\" }}").unwrap(),
            }
        }
        writeln!(out).unwrap();
    }

    emit_compiler_sections(&mut out, p);
    emit_platform_sections(&mut out, p);
    emit_profiles(&mut out);

    out
}

fn sanitise_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '-' })
        .collect::<String>()
        .trim_matches('-')
        .to_string()
}

// ── Shared emit helpers ───────────────────────────────────────────────────────

fn emit_languages(out: &mut String, p: &ImportedProject) {
    for (key, lang) in &p.languages {
        writeln!(out, "[language.{key}]").unwrap();
        if let Some(std) = &lang.std {
            writeln!(out, "std = \"{std}\"").unwrap();
        }
        writeln!(out).unwrap();
    }
}

fn emit_dependencies(out: &mut String, p: &ImportedProject) {
    if !p.dependencies.is_empty() {
        writeln!(out, "[dependencies]").unwrap();
        for (name, dep) in &p.dependencies {
            match dep {
                ImportedDep::System(s) => writeln!(out, "{name} = {{ system = \"{s}\" }}").unwrap(),
                ImportedDep::Version(v) => writeln!(out, "{name} = \"{v}\"").unwrap(),
                ImportedDep::Path(r) => writeln!(out, "{name} = {{ path = \"{r}\" }}").unwrap(),
            }
        }
        writeln!(out).unwrap();
    }
}

fn emit_compiler_sections(out: &mut String, p: &ImportedProject) {
    writeln!(out, "[compiler]").unwrap();
    writeln!(out, "backend   = \"auto\"").unwrap();
    writeln!(out, "opt-level = 2").unwrap();
    writeln!(out, "debug     = false").unwrap();
    writeln!(out, "warnings  = \"all\"").unwrap();
    if !p.compiler.defines.is_empty() {
        writeln!(out, "defines   = {}", fmt_string_array(&p.compiler.defines)).unwrap();
    }
    if !p.compiler.flags.is_empty() {
        writeln!(out, "flags     = {}", fmt_string_array(&p.compiler.flags)).unwrap();
    }
    writeln!(out).unwrap();

    if !p.compiler.include_paths.is_empty() {
        writeln!(out, "[compiler.includes]").unwrap();
        writeln!(out, "paths = {}", fmt_string_array(&p.compiler.include_paths)).unwrap();
        writeln!(out).unwrap();
    }
}

fn emit_platform_sections(out: &mut String, p: &ImportedProject) {
    for (key, ov) in &p.platforms {
        if !ov.dependencies.is_empty() {
            writeln!(out, "[platform.{key}.dependencies]").unwrap();
            for (name, dep) in &ov.dependencies {
                match dep {
                    ImportedDep::System(s) => writeln!(out, "{name} = {{ system = \"{s}\" }}").unwrap(),
                    ImportedDep::Version(v) => writeln!(out, "{name} = \"{v}\"").unwrap(),
                    ImportedDep::Path(r) => writeln!(out, "{name} = {{ path = \"{r}\" }}").unwrap(),
                }
            }
            writeln!(out).unwrap();
        }
        if !ov.defines.is_empty() || !ov.flags.is_empty() {
            writeln!(out, "[platform.{key}.compiler]").unwrap();
            if !ov.defines.is_empty() {
                writeln!(out, "defines = {}", fmt_string_array(&ov.defines)).unwrap();
            }
            if !ov.flags.is_empty() {
                writeln!(out, "flags   = {}", fmt_string_array(&ov.flags)).unwrap();
            }
            writeln!(out).unwrap();
        }
        if !ov.include_paths.is_empty() {
            writeln!(out, "[platform.{key}.compiler.includes]").unwrap();
            writeln!(out, "paths = {}", fmt_string_array(&ov.include_paths)).unwrap();
            writeln!(out).unwrap();
        }
    }
}

fn emit_profiles(out: &mut String) {
    writeln!(out, "[profile.dev]").unwrap();
    writeln!(out, "opt-level = 0").unwrap();
    writeln!(out, "debug     = true").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "[profile.release]").unwrap();
    writeln!(out, "opt-level = 3").unwrap();
    writeln!(out, "lto       = true").unwrap();
    writeln!(out, "strip     = true").unwrap();
    writeln!(out, "debug     = false").unwrap();
}

fn fmt_string_array(items: &[String]) -> String {
    let mut s = String::from("[");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push('"');
        s.push_str(&escape_string(item));
        s.push('"');
    }
    s.push(']');
    s
}

fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::super::*;
    use super::*;

    #[test]
    fn workspace_with_two_libs_and_one_bin() {
        let mut p = ImportedProject::default();
        p.name = Some("demo".into());
        p.version = Some("1.0.0".into());
        p.libs.push(ImportedLib { name: "foo".into(), lib_type: "static".into(), src: "src/foo/".into(), include: None });
        p.libs.push(ImportedLib { name: "bar".into(), lib_type: "shared".into(), src: "src/bar/".into(), include: None });
        p.bins.push(crate::ImportedBin { name: "app".into(), src: "src/main.cpp".into() });

        let ws = to_workspace_toml(&p);

        // Root has [workspace] with both lib members + the bin member.
        assert!(ws.root_toml.contains("[workspace]"));
        assert!(ws.root_toml.contains("\"foo/\""));
        assert!(ws.root_toml.contains("\"bar/\""));
        assert!(ws.root_toml.contains("\"demo/\""), "bin member should use project name");

        // Three members: foo, bar, demo.
        assert_eq!(ws.members.len(), 3);

        let (foo_dir, foo_toml) = ws.members.iter().find(|(d, _)| d == "foo").unwrap();
        assert_eq!(foo_dir, "foo");
        assert!(foo_toml.contains("[lib]"));
        assert!(foo_toml.contains("type    = \"static\""));

        let (bar_dir, bar_toml) = ws.members.iter().find(|(d, _)| d == "bar").unwrap();
        assert_eq!(bar_dir, "bar");
        assert!(bar_toml.contains("type    = \"shared\""));

        let (_, bin_toml) = ws.members.iter().find(|(d, _)| d == "demo").unwrap();
        assert!(bin_toml.contains("[[bin]]"));
        // Binary member should have path deps to both libraries.
        assert!(bin_toml.contains("foo = { path = \"../foo\" }"));
        assert!(bin_toml.contains("bar = { path = \"../bar\" }"));
    }

    #[test]
    fn minimal_project_emits_package_and_compiler() {
        let p = ImportedProject {
            name: Some("hello".into()),
            version: Some("0.2.0".into()),
            ..Default::default()
        };
        let toml = to_toml(&p);
        assert!(toml.contains("name        = \"hello\""));
        assert!(toml.contains("version     = \"0.2.0\""));
        assert!(toml.contains("[compiler]"));
        assert!(toml.contains("[profile.dev]"));
        assert!(toml.contains("[profile.release]"));
    }

    #[test]
    fn notes_are_emitted_as_freight_comments() {
        let mut p = ImportedProject::default();
        p.push_note("add_subdirectory(sub) not imported");
        let toml = to_toml(&p);
        assert!(toml.contains("# FREIGHT: add_subdirectory(sub) not imported"));
    }

    #[test]
    fn empty_description_is_omitted() {
        let p = ImportedProject {
            name: Some("hello".into()),
            ..Default::default()
        };
        let toml = to_toml(&p);
        assert!(!toml.contains("description"));
        assert!(!toml.contains("license"));
    }

    #[test]
    fn populated_description_is_emitted() {
        let p = ImportedProject {
            name: Some("hello".into()),
            description: Some("a short description".into()),
            ..Default::default()
        };
        let toml = to_toml(&p);
        assert!(toml.contains("description = \"a short description\""));
    }

    #[test]
    fn platform_overlay_emits_nested_tables() {
        let mut p = ImportedProject::default();
        p.name = Some("hello".into());
        let win = p.platform_mut("windows");
        win.dependencies.insert("ws2_32".into(), ImportedDep::System("ws2_32".into()));
        win.defines.push("WIN_BUILD".into());
        win.include_paths.push("third_party/win-include/".into());
        let toml = to_toml(&p);
        assert!(toml.contains("[platform.windows.dependencies]"));
        assert!(toml.contains("ws2_32 = { system = \"ws2_32\" }"));
        assert!(toml.contains("[platform.windows.compiler]"));
        assert!(toml.contains("defines = [\"WIN_BUILD\"]"));
        assert!(toml.contains("[platform.windows.compiler.includes]"));
        assert!(toml.contains("paths = [\"third_party/win-include/\"]"));
    }

    #[test]
    fn empty_platform_overlay_omits_section() {
        let mut p = ImportedProject::default();
        p.name = Some("hello".into());
        // Touch the entry so it exists but stays empty.
        p.platform_mut("linux");
        let toml = to_toml(&p);
        assert!(!toml.contains("[platform.linux"));
    }

    #[test]
    fn system_and_path_deps_emit_tables() {
        let mut p = ImportedProject::default();
        p.dependencies
            .insert("openssl".into(), ImportedDep::System("openssl".into()));
        p.dependencies
            .insert("myutils".into(), ImportedDep::Path("../myutils".into()));
        let toml = to_toml(&p);
        assert!(toml.contains("openssl = { system = \"openssl\" }"));
        assert!(toml.contains("myutils = { path = \"../myutils\" }"));
    }
}
